import type { AppConfig } from '@/types/app-config';

/**
 * Default config for this deployment.
 * This is the ONLY file that changes per deployment until Supabase is connected.
 * See docs/plans/backend-plan.md for migration steps.
 */
export const defaultConfig: AppConfig = {
  branding: {
    appName: 'Sea Smoke Fishing Club',
    primaryColor: '#193da9',
    accentColor: '#f6ab03',
    font: 'inter',
    logoUrl: null,
    faviconUrl: null,
    darkMode: false,
  },

  navigation: [
    { key: 'home', label: 'Home', href: '/', icon: 'Home', enabled: true },
    { key: 'tours', label: 'Fishing Charters', href: '/tours', icon: 'Ship', enabled: true },
    { key: 'about', label: 'About', href: '/about', icon: 'Info', enabled: true },
    { key: 'contact', label: 'Contact', href: '/contact', icon: 'Mail', enabled: true },
  ],

  features: {
    bookings: true,
    tours: true,
    reports: true,
    clientPortal: false,
    notifications: true,
  },

  homepage: {
    sectionOrder: ['stats', 'tours', 'whyus', 'reviews', 'gallery', 'cta'],
    hero: {
      enabled: true,
      size: 'fullscreen',
      
      showEyebrow: true,
      eyebrow: 'Join the best on the water',
      
      headline: "Cast Your Line",
      italicText: 'Into the Deep',
      
      showSubtitle: true,
      subtitle: 'Experience the thrill of deep sea fishing and connect with a community of passionate anglers. Whether you are a beginner or a seasoned pro, there is a spot for you in our club.',
      
      showPrimaryCta: true,
      primaryCtaLabel: 'Join the Club',
      primaryCtaHref: '/bookings',
      
      showSecondaryCta: true,
      secondaryCtaLabel: 'View Events',
      secondaryCtaHref: '/events',
      
      imageUrl: '/images/hero/hero.jpg',
    },

    stats: {
      enabled: true,
      backgroundColor: '#ffffff',
      title: '',
      subtitle: '',
      eyebrow: '',
      items: [
        { enabled: true, value: '15+',    label: 'Years Active' },
        { enabled: true, value: '500+',   label: 'Club Members' },
        { enabled: true, value: '100+',   label: 'Annual Events' },
        { enabled: true, value: '4.9/5',  label: 'Community Rating' },
      ],
    },



    tours: {
      enabled: true,
      backgroundColor: '#fafafa',
      eyebrow: 'Our Fishing Charters',
      title: 'Deep Sea Fishing Experiences',
      subtitle: 'Book unforgettable deep sea fishing charters and guided tours. Catch trophy fish with expert captains.',
      items: [
        {
          enabled: true,
          badge: 'Most Popular',
          title: 'Deep Sea Excursion',
          description:
            'Join us for a full day of deep sea fishing chasing marlin, tuna, and sailfish.',
          duration: 'Full Day',
          rating: 5.0,
          imageUrl: '/images/hero/hero.jpg',
          gallery: [
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
          ],
        },
        {
          enabled: true,
          badge: 'Beginner Friendly',
          title: 'Inshore Catch & Release',
          description:
            'A relaxed half-day trip exploring the coastal waters, perfect for families and beginners.',
          duration: 'Half Day',
          rating: 4.8,
          imageUrl: '/images/hero/hero.jpg',
          gallery: [
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
          ],
        },
        {
          enabled: true,
          badge: 'Competitive',
          title: 'Annual Summer Tournament',
          description:
            'Compete with fellow members in our biggest catch-and-release tournament of the year.',
          duration: '2 Days',
          rating: 5.0,
          imageUrl: '/images/hero/hero.jpg',
          gallery: [
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
          ],
        },
      ],
    },

    reviews: {
      enabled: true,
      backgroundColor: '#020617',
      eyebrow: 'Excellent on TripAdvisor',
      title: 'Guest reviews',
      subtitle: '',
      items: [
        {
          enabled: true,
          quote:
            'Joining this club was the best decision I ever made. I have learned so much from the veteran anglers and made lifelong friends on the water.',
          name: 'Michael Thompson',
          location: 'Local Member',
        },
        {
          enabled: true,
          quote:
            'The deep sea excursions are incredibly well organized. The captains know exactly where the fish are biting. Highly recommend the summer tournament!',
          name: 'Sarah Jenkins',
          location: 'Tournament Winner',
        },
        {
          enabled: true,
          quote:
            'A fantastic community that truly cares about marine conservation. They teach sustainable fishing practices to all new members.',
          name: 'David & Lisa',
          location: 'Family Members',
        },
      ],
    },

    whyUs: {
      enabled: true,
      backgroundColor: '#ffffff',
      imageUrl: '/images/hero/hero.jpg',
      eyebrow: 'Why Fish With Us',
      title: 'Guided by expertise, inspired by the ocean',
      subtitle: '',
      items: [
        {
          enabled: true,
          icon: 'Shield',
          title: 'Expert Community',
          body: 'Learn from seasoned professionals with decades of experience on the local waters.',
        },
        {
          enabled: true,
          icon: 'Globe',
          title: 'Exclusive Events',
          body: 'Get access to members-only tournaments, chartered trips, and gear demonstrations.',
        },
        {
          enabled: true,
          icon: 'Leaf',
          title: 'Conservation First',
          body: 'We practice and promote sustainable catch-and-release fishing to protect our oceans.',
        },
      ],
    },

    gallery: {
      enabled: true,
      backgroundColor: '#ffffff',
      indicatorColor: '#000000',
      title: 'Catch Gallery',
      subtitle: '',
      eyebrow: '',
      items: [
        { enabled: true, imageUrl: '/images/hero/hero.jpg', caption: 'Giant Marlin Catch' },
        { enabled: true, imageUrl: '/images/hero/hero.jpg', caption: 'Summer Tournament 2024' },
        { enabled: true, imageUrl: '/images/hero/hero.jpg', caption: 'Sunset Fishing' },
        { enabled: true, imageUrl: '/images/hero/hero.jpg', caption: 'Group Trip' },
      ],
    },

    ctaBanner: {
      enabled: true,
      backgroundColor: '#193da9',
      headline: 'Ready to Catch the Big One?',
      subtitle: 'Become a member today and get access to exclusive events, trips, and premium gear discounts.',
      ctaLabel: 'Join the Club Now',
      ctaHref: '/bookings',
    },

    footer: {
      enabled: true,
      backgroundColor: '#020617',
      description: 'A passionate community of anglers dedicated to the sport of fishing and marine conservation. Join us on the water.',
      contact: {
        location: 'Coastal Harbor Marina, Dock 4',
        phone: '+1 (555) 019-8372',
        email: 'info@seasmokefishingclub.com',
        workingDays: 'Mon - Sun: 5:00 AM - 8:00 PM',
        workingHours: 'Always on the water',
      },
      socials: {
        enabled: true,
        items: [
          { enabled: true, icon: 'Facebook', url: '#' },
          { enabled: true, icon: 'Instagram', url: '#' },
          { enabled: true, icon: 'Whatsapp', url: '#' },
          { enabled: true, icon: 'Tiktok', url: '#' },
        ],
      },
      quickLinks: {
        enabled: true,
        items: [
          { enabled: true, label: 'Home', href: '/' },
          { enabled: true, label: 'Events', href: '#' },
          { enabled: true, label: 'Membership', href: '#' },
        ],
      },
      topPackages: {
        enabled: true,
        items: [
          { enabled: true, label: 'Deep Sea Charter', href: '#' },
          { enabled: true, label: 'Inshore Fishing', href: '#' },
          { enabled: true, label: 'Tournament Entry', href: '#' },
          { enabled: true, label: 'Beginner Classes', href: '#' },
          { enabled: true, label: 'Gear Rental', href: '#' },
        ],
      },
      bottomLinks: {
        enabled: true,
        items: [
          { enabled: true, label: 'Privacy Policy', href: '#' },
          { enabled: true, label: 'Terms & Conditions', href: '#' },
          { enabled: true, label: 'Club Rules', href: '#' },
        ],
      },
    },
  },

  toursPage: {
    hero: {
      enabled: true,
      backgroundColor: '#193da9',
      showEyebrow: true,
      eyebrow: 'SINGLE DAY TRIPS & EXPEDITIONS',
      headline: 'Fishing Charters',
      italicText: '& Excursions',
      showSubtitle: true,
      subtitle: 'Guided deep sea fishing charters and coastal excursions along Kenya\'s premier waters. Catch trophy marlin, sailfish, tuna, and giant trevally with expert captains.',
      showPrimaryCta: false,
      primaryCtaLabel: '',
      primaryCtaHref: '',
      showSecondaryCta: false,
      secondaryCtaLabel: '',
      secondaryCtaHref: '',
      imageUrl: '/images/hero/hero.jpg',
      size: 'medium',
    },
    tours: {
      enabled: true,
      backgroundColor: '#f5f5f0',
      eyebrow: 'OUR FISHING CHARTERS',
      title: 'Explore Our Fishing Experiences',
      subtitle: 'From relaxed inshore family outings to full-day big game billfish safaris, choose your adventure on the ocean.',
      items: [
        {
          enabled: true,
          slug: 'marlin-sailfish-safari',
          badge: 'Most Popular',
          title: 'Full-Day Big Game Marlin & Sailfish Safari',
          description: 'Embark on an adrenaline-pumping offshore expedition pursuing blue marlin, black marlin, striped marlin, and sailfish with tournament-grade heavy tackle.',
          duration: 'Guided 6 - 8 hours Tour',
          rating: 5.0,
          imageUrl: '/images/hero/hero.jpg',
          location: 'Watamu Marine Park & Malindi Trench, Kenya',
          schedule: 'Morning Slots (November To March)',
          groupType: 'Families · Private · Solo Anglers · Groups',
          gallery: [
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
          ],
          overview: 'Start your full-day deep-sea expedition with thrilling dolphin watching in the open sea, followed by big game sportfishing along the famous Kenyan drop-off and Malindi trench. Target marlin, sailfish, yellowfin tuna, and wahoo with world-class tackle and fighting chairs.',
          included: [
            'Dolphin spotting & coastal cruise with certified marine guide',
            'Heavy tackle, Penn & Shimano rods, outriggers, fighting chair',
            'Live bait, lures, and tournament spread prepared by crew',
            'Marine park conservation permits & fishing licenses included',
            'Freshly prepared island seafood lunch & ice-cold drinks',
            'Life jackets, Garmin GPS sonar navigation, and emergency safety gear',
            'Complimentary high-res photo package upon request',
          ],
          showIncluded: true,
          notIncluded: [
            'Crew gratuities and tips (optional)',
            'Hotel pickup & return transfers (available on request)',
            'Personal swimwear & beach towels',
            'Alcoholic spirits (BYOB welcome)',
          ],
          showNotIncluded: true,
          whyChoose: [
            'Combines big-game billfish hunting, dolphin watching, and ocean exploration',
            'Twin-engine offshore sportfishing vessel with shaded deck',
            'IGFA-certified captain with 20+ years navigating Kenyan waters',
            'Strict catch-and-release conservation policy for all billfish',
            'All-inclusive private charter with premium gear and catering',
          ],
          showWhyChoose: true,
          knowBeforeYouGo: [
            'Departure: 6:00 AM from Watamu Marine Park Gate',
            'Duration: Approx. 8 hours',
            'Availability: Daily during peak season (November - April)',
            'What to bring: Polarized sunglasses, reef-safe sunscreen, light jacket, deck shoes',
            'Booking: Reserve in advance to secure your boat and date',
          ],
          showKnowBeforeYouGo: true,
          price: 'Contact for pricing',
          priceLabel: 'Contact for pricing',
          href: '/tours/marlin-sailfish-safari',
        },
        {
          enabled: true,
          slug: 'inshore-reef-fishing',
          badge: 'Beginner Friendly',
          title: 'Inshore Reef & Light Tackle Catch & Release',
          description: 'A relaxed coastal outing exploring rich reefs, perfect for families and novices targeting kingfish, snapper, barracuda, and bonito.',
          duration: 'Guided 4 hours Tour',
          rating: 4.8,
          imageUrl: '/images/hero/hero.jpg',
          location: 'Watamu Inshore Reefs & Mida Creek, Kenya',
          schedule: 'Morning & Afternoon Slots (All Year)',
          groupType: 'Families · Kids · Beginners · Private Groups',
          gallery: [
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
          ],
          overview: 'Enjoy a scenic, calmer coastal expedition exploring sheltered reefs and mangrove channels. Ideal for families and junior anglers looking for constant action with kingfish, trevally, snapper, and bonito.',
          included: [
            'Light tackle spinning rods, jigs, and trolling gear',
            'Hands-on coaching and baiting assistance from crew',
            'Snorkeling gear & reef exploration stop',
            'Soft drinks, mineral water, and tropical fruit snacks',
            'Life jackets for all ages (including child sizes)',
          ],
          showIncluded: true,
          notIncluded: [
            'Crew gratuities and tips (optional)',
            'Hotel pickup & return transfers (available on request)',
            'Personal swimwear & beach towels',
          ],
          showNotIncluded: true,
          whyChoose: [
            'Calm waters, perfect for families and children',
            'Consistent multi-species action on light tackle',
            'Scenic mangrove creek tour combined with reef fishing',
          ],
          showWhyChoose: true,
          knowBeforeYouGo: [
            'Departure: 7:30 AM or 1:30 PM from Watamu Bay',
            'Duration: Approx. 4 hours',
            'What to bring: Swimwear, sunglasses, sunscreen, hat',
            'Booking: Available daily all year round',
          ],
          showKnowBeforeYouGo: true,
          price: 'Contact for pricing',
          priceLabel: 'Contact for pricing',
          href: '/tours/inshore-reef-fishing',
        },
        {
          enabled: true,
          slug: 'yellowfin-tuna-dorado',
          badge: 'Action Packed',
          title: 'Deep Sea Yellowfin Tuna & Dorado Trolling',
          description: 'High-speed trolling and live-baiting off the drop-off for acrobatic mahi-mahi (dorado), hard-fighting wahoo, and schooling yellowfin tuna.',
          duration: 'Guided 6 hours Tour',
          rating: 4.9,
          imageUrl: '/images/hero/hero.jpg',
          location: 'North Kenya Banks & Offshore Drop-Off',
          schedule: 'Morning Slots (August To March)',
          groupType: 'Sportfishers · Private Charters · Anglers',
          gallery: [
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
          ],
          overview: 'Head offshore to the temperature breaks and bird frenzies where schools of yellowfin tuna and dorado feed actively on flying fish. Experience explosive surface strikes on poppers and fast trolling lures.',
          included: [
            'Medium & heavy trolling tackle with Shimano Tiagra reels',
            'Surface poppers, diving plugs, and rigged ballyhoo bait',
            'Experienced sportfishing skipper & first mate',
            'Cold beer, soft drinks, sandwiches, and fresh fruit',
          ],
          showIncluded: true,
          notIncluded: [
            'Crew gratuities and tips (optional)',
            'Hotel pickup & return transfers (available on request)',
            'Personal apparel & beach towels',
          ],
          showNotIncluded: true,
          whyChoose: [
            'Fast-paced reel-screaming surface action',
            'Target delicious game fish with option to retain edible tuna/dorado',
            'High success rate on offshore current rips',
          ],
          showWhyChoose: true,
          knowBeforeYouGo: [
            'Departure: 6:00 AM from Watamu Marine Gate',
            'Duration: Approx. 6 hours',
            'What to bring: Sunglasses, hat, non-slip footwear',
          ],
          showKnowBeforeYouGo: true,
          price: 'Contact for pricing',
          priceLabel: 'Contact for pricing',
          href: '/tours/yellowfin-tuna-dorado',
        },
        {
          enabled: true,
          slug: 'broadbill-swordfish-night',
          badge: 'Night Adventure',
          title: 'Broadbill Swordfish Night Drift Expedition',
          description: 'Experience the magic of deep-sea fishing under the stars. Drift deep squid baits along oceanic trenches for the gladiator of the sea.',
          duration: 'Guided 10 hours Overnight Tour',
          rating: 5.0,
          imageUrl: '/images/hero/hero.jpg',
          location: 'Rift Valley Continental Trench, Kenya',
          schedule: 'Sunset & Night Slots (October To March)',
          groupType: 'Experienced Anglers · Private Only',
          gallery: [
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
            '/images/hero/hero.jpg',
          ],
          overview: 'Broadbill swordfish are the ultimate prize in sportfishing. Drift offshore under starlight with hydro-glow deep lights and rigged squid baits at 1,000+ feet depths for a battle of a lifetime.',
          included: [
            'Custom deep-drop rods, electric reels & 80lb stand-up tackle',
            'Hydro-glow underwater attractor lights & deep-sea squid',
            'Overnight dinner, hot coffee, snacks, and refreshments',
            'Full navigation radar and safety equipment',
          ],
          showIncluded: true,
          notIncluded: [
            'Crew gratuities and tips (optional)',
            'Hotel pickup & return transfers (available on request)',
            'Personal heavy clothing & toiletries',
          ],
          showNotIncluded: true,
          whyChoose: [
            'Exclusive expedition for passionate big-game anglers',
            'Pursue the powerful "Gladiator of the Sea"',
            'Unforgettable night on the Indian Ocean under starlit skies',
          ],
          showWhyChoose: true,
          knowBeforeYouGo: [
            'Departure: 5:00 PM (Return approx. 3:00 AM)',
            'Duration: Approx. 10 hours',
            'What to bring: Warm layers, windbreaker jacket, sea-sickness remedy',
          ],
          showKnowBeforeYouGo: true,
          price: 'Contact for pricing',
          priceLabel: 'Contact for pricing',
          href: '/tours/broadbill-swordfish-night',
        },
      ],
    },
    bookingForm: {
      enabled: true,
      title: 'Book This Charter',
      subtitle: 'Reserve your private expedition on the water.',
      buttonText: 'Submit Reservation',
      accessKey: '',
      fields: [
        {
          id: 'fullName',
          label: 'Full Name',
          type: 'text',
          placeholder: 'e.g. John Doe',
          required: true,
          halfWidth: true,
          enabled: true,
        },
        {
          id: 'email',
          label: 'Email Address',
          type: 'email',
          placeholder: 'name@example.com',
          required: true,
          halfWidth: true,
          enabled: true,
        },
        {
          id: 'phone',
          label: 'Phone Number',
          type: 'tel',
          placeholder: '+254 700 000 000',
          required: true,
          halfWidth: true,
          enabled: true,
        },
        {
          id: 'date',
          label: 'Preferred Date',
          type: 'date',
          required: false,
          halfWidth: true,
          enabled: true,
        },
        {
          id: 'guests',
          label: 'Number of Guests',
          type: 'select',
          options: [
            '1 Guest',
            '2 Guests',
            '3 Guests',
            '4 Guests',
            '5 Guests',
            '6-8 Guests (Private Boat)',
            '8+ Large Group',
          ],
          required: false,
          halfWidth: false,
          enabled: true,
        },
        {
          id: 'transfer',
          label: 'Include Hotel Pick & Drop Transfer',
          type: 'checkbox',
          required: false,
          halfWidth: false,
          enabled: true,
        },
        {
          id: 'notes',
          label: 'Special Requests & Notes',
          type: 'textarea',
          placeholder: 'Target species, dietary requirements, experience level...',
          required: false,
          halfWidth: false,
          enabled: true,
        },
      ],
    },
  },

  contactPage: {
    hero: {
      enabled: true,
      backgroundColor: '#000000',
      showEyebrow: true,
      eyebrow: 'Get in Touch',
      headline: "Let's plan your",
      italicText: 'adventure',
      showSubtitle: true,
      subtitle: 'Have a question about our charters or want to book a trip? Our team is ready to help you plan your perfect day on the water.',
      showPrimaryCta: false,
      primaryCtaLabel: '',
      primaryCtaHref: '',
      showSecondaryCta: false,
      secondaryCtaLabel: '',
      secondaryCtaHref: '',
      imageUrl: '/images/hero/hero.jpg',
      size: 'medium',
    },
    contact: {
      enabled: true,
      backgroundColor: '#f5f5f0',
      location: 'Mombasa, Kenya',
      locationLink: 'https://maps.google.com/?q=Mombasa',
      phone: '+254 123 456 789',
      email: 'info@seasmokekenya.com',
      whatsapp: '+254 123 456 789',
      tripAdvisorLink: 'https://tripadvisor.com',
    },
    form: {
      enabled: true,
      backgroundColor: '#ffffff',
      title: 'Send a message',
      subtitle: 'We usually respond within 2-4 hours.',
      buttonText: 'Submit request',
      accessKey: '',
      fields: [
        {
          id: 'name',
          label: 'Full Name',
          type: 'text',
          placeholder: 'Jane Doe',
          required: true,
          halfWidth: true,
          enabled: true,
        },
        {
          id: 'email',
          label: 'Email Address',
          type: 'email',
          placeholder: 'jane@example.com',
          required: true,
          halfWidth: true,
          enabled: true,
        },
        {
          id: 'phone',
          label: 'Phone Number',
          type: 'tel',
          placeholder: '+254 ...',
          required: false,
          halfWidth: true,
          enabled: true,
        },
        {
          id: 'subject',
          label: 'Subject',
          type: 'select',
          options: [
            'General Inquiry',
            'Fishing Charter Booking',
            'Tournaments & Events',
            'Custom Coastal Safari',
            'Feedback & Questions',
          ],
          required: false,
          halfWidth: true,
          enabled: true,
        },
        {
          id: 'message',
          label: 'Your Message',
          type: 'textarea',
          placeholder: 'Tell us about your next big fishing trip...',
          required: true,
          halfWidth: false,
          enabled: true,
        },
      ],
    },
    faq: {
      enabled: true,
      backgroundColor: '#f5f5f0', // From screenshot
      title: 'Commonly asked questions',
      subtitle: '',
      eyebrow: 'QUICK ANSWERS',
      items: [
        {
          enabled: true,
          question: 'What is the best time for deep sea fishing?',
          answer: 'The peak season runs from August to March when Marlin and Sailfish are most abundant in Kenyan waters.',
        },
        {
          enabled: true,
          question: 'Do I need to bring my own fishing gear?',
          answer: 'No, all premium rods, reels, and tackle are provided on our charters. However, you\'re welcome to bring your favorite gear.',
        },
        {
          enabled: true,
          question: 'Is it catch and release?',
          answer: 'We strictly enforce a catch-and-release policy for all Billfish (Marlin, Sailfish) to support marine conservation efforts.',
        },
      ],
    },
  },

  aboutPage: {
    hero: {
      enabled: true,
      backgroundColor: '#000000',
      showEyebrow: true,
      eyebrow: 'OUR HERITAGE',
      headline: 'Born on the tides,',
      italicText: 'bound by the deep',
      showSubtitle: true,
      subtitle:
        'Pioneering premier big-game sportfishing and marine conservation along the pristine Kenyan coastline.',
      showPrimaryCta: false,
      primaryCtaLabel: '',
      primaryCtaHref: '',
      showSecondaryCta: false,
      secondaryCtaLabel: '',
      secondaryCtaHref: '',
      imageUrl: '/images/hero/hero.jpg',
      size: 'large',
    },
    story: {
      enabled: true,
      backgroundColor: '#ffffff',
      eyebrow: 'OUR VOYAGE',
      title: "The heartbeat of Kenya's coastal waters and big-game tradition.",
      paragraphs: [
        {
          enabled: true,
          text: 'Founded on the rugged shores of the Kenya Coast, Sea Smoke Fishing Club was born from a singular passion: to deliver world-class sportfishing adventures while championing ocean stewardship. For our anglers, a charter into the deep is more than a sport — it is an intimate encounter with the raw power of the open sea.',
        },
        {
          enabled: true,
          text: 'Over 15 years, we have worked alongside coastal maritime communities and marine biologists to pioneer catch-and-release tagging programs, protect vital billfish breeding grounds, and ensure our blue waters thrive for generations of anglers to come.',
        },
      ],
      imageUrl: '/images/hero/hero.jpg',
      imageAlt: 'Sea Smoke Fishing Club crew on the water',
    },
    values: {
      enabled: true,
      backgroundColor: '#fafafa',
      title: 'Guided by the tides',
      subtitle:
        'Our core values steer every expedition we launch, every hook we set, and every relationship we nurture on and off the water.',
      eyebrow: 'CORE VALUES',
      items: [
        {
          enabled: true,
          icon: 'Anchor',
          title: 'Marine Conservation',
          description:
            'Pioneering strict billfish catch-and-release protocols and active marine habitat preservation.',
        },
        {
          enabled: true,
          icon: 'Compass',
          title: 'Master Seamanship',
          description:
            'Seasoned captains with decades of navigational mastery across the East African swell.',
        },
        {
          enabled: true,
          icon: 'Users',
          title: 'Community & Craft',
          description:
            'Empowering coastal fishing communities through fair maritime partnerships and training.',
        },
        {
          enabled: true,
          icon: 'Star',
          title: 'Unmatched Excellence',
          description:
            'State-of-the-art sportfishing rigs, tournament-grade tackle, and bespoke hospitality at sea.',
        },
      ],
    },
    team: {
      enabled: true,
      backgroundColor: '#ffffff',
      eyebrow: 'THE CREW',
      title: 'Meet your skippers & naturalists',
      subtitle:
        "Our crew members aren't just master captains; they are custodians of the Indian Ocean, carrying decades of maritime instincts.",
      items: [
        {
          enabled: true,
          name: 'Captain Peter K.',
          role: 'Head Skipper',
          quote: '"The deep blue speaks to those who respect its currents."',
          imageUrl: '/images/hero/hero.jpg',
        },
        {
          enabled: true,
          name: 'Sarah O.',
          role: 'Marine Biologist & Tagging Specialist',
          quote: '"Every billfish tagged brings us closer to understanding our ocean\'s secrets."',
          imageUrl: '/images/hero/hero.jpg',
        },
        {
          enabled: true,
          name: 'David M.',
          role: 'Master Navigator',
          quote: '"The ocean has a memory; we read every ripple and reef."',
          imageUrl: '/images/hero/hero.jpg',
        },
      ],
    },
    impact: {
      enabled: true,
      backgroundColor: '#0f172a',
      title: 'Our impact by the numbers',
      subtitle:
        "Marine conservation isn't an afterthought; it is our compass. Through every charter, we deliver measurable protection for our oceans.",
      stats: [
        { enabled: true, value: '1,200+', label: 'BILLFISH TAGGED & RELEASED' },
        { enabled: true, value: '15+', label: 'YEARS OF VOYAGES' },
        { enabled: true, value: '100%', label: 'CATCH & RELEASE BILLFISH' },
        { enabled: true, value: '350nm', label: 'COASTLINE MONITORED' },
      ],
      partnersCard: {
        title: 'Our Conservation Partners',
        icon: 'ShieldCheck',
        partners: [
          'The Billfish Foundation',
          'Kenya Wildlife Service',
          'Marine Megafauna',
          'East Africa Ocean Trust',
        ],
      },
    },
    cta: {
      enabled: true,
      backgroundColor: '#fafafa',
      title: 'Answer the call of the deep',
      subtitle:
        'Whether chasing trophy marlin on the open banks or enjoying an inshore excursion, your next great maritime adventure begins here.',
      primaryCta: {
        enabled: true,
        label: 'Book Your Charter',
        href: '/contact',
      },
      secondaryCta: {
        enabled: true,
        label: 'Get in Touch',
        href: '/contact',
      },
    },
  },
};

