import type { AppConfig, TourItem } from '@/types/app-config';

/**
 * Default tour and charter list items for Sea Smoke Kenya.
 */
export const defaultTourItems: TourItem[] = [
  {
    id: 'charter-full-day-deep-sea-excursion',
    enabled: true,
    deleted: false,
    slug: 'full-day-big-game-marlin-sailfish-safari',
    href: '/tours/full-day-big-game-marlin-sailfish-safari',
    badge: 'Most Popular',
    showBadge: true,
    title: 'Full - day deep Sea Excursion',
    showTitle: true,
    price: 'Contact for pricing',
    priceLabel: 'Contact for pricing',
    showPrice: true,
    rating: 5,
    showRating: true,
    duration: '8h',
    showDuration: true,
    imageUrl:
      'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/tours/1787372351282-8j4thg01yip.jpg',
    heroImageUrl: '/images/hero/hero.jpg',
    indicatorColor: '#ffffff',
    location: 'watamu coastal line',
    showLocation: true,
    schedule: 'Any day',
    showSchedule: true,
    groupType: 'Families · Private · Groups',
    showGroupType: true,
    description:
      'Spend a full day chasing marlin, sailfish, tuna, and dorado in the Indian Ocean. Perfect for serious anglers seeking big‑game fishing adventures.',
    overview:
      'Spend an unforgettable day offshore with Sea Smoke Kenya exploring the Indian Ocean’s most productive fishing grounds. This full‑day adventure (6:30 AM – 4:00 PM) gives you maximum time to chase trophy species including sailfish, marlin, tuna, wahoo, kingfish, and dorado. Guided by our experienced crew, you’ll enjoy professional equipment, fresh bait, and personalized support throughout the trip.\n\nWhether you’re a seasoned angler or a first‑time visitor, this excursion combines the thrill of big‑game fishing with the beauty of Kenya’s coastline. Expect breathtaking ocean views, expert guidance, and the chance to land some of the world’s most exciting game fish.',
    included: [
      'Live bait & fishing lures',
      'Lunch box',
      'Fresh fruits',
      'Soft drinks',
      'Fishing equipment provided',
      'Experienced crew & captain guidance',
    ],
    showIncluded: true,
    whyChoose: [
      'Alcoholic beverages',
      'Personal travel insurance',
      'Tips/gratuities for crew',
      'Fishing license/permits (if required)',
      'Transport to/from departure point (unless arranged)',
    ],
    showWhyChoose: true,
    knowBeforeYouGo: [
      'Bring sunscreen, hat, sunglasses, and light clothing for sun protection.',
      'Carry seasickness medication if prone to motion sickness.',
      'Keep valuables safe and waterproof (phone, camera).',
      'Catch‑and‑release is encouraged for billfish (marlin, sailfish) to support conservation.',
      'Minimum age recommended: 8 years (children must be accompanied by adults).',
      'Trips are weather‑dependent; rescheduling may occur for safety.',
    ],
    showKnowBeforeYouGo: true,
    notIncluded: [
      'Crew gratuities and tips (optional)',
      'Hotel pickup & return transfers',
      'Personal swimwear & towels',
    ],
    showNotIncluded: true,
    gallery: [
      'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/tours/1787373139053-uu2u6txh7rh.jpg',
      'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/tours/1787372351282-8j4thg01yip.jpg',
      'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/tours/1787373139053-uu2u6txh7rh.jpg',
    ],
  },
  {
    id: 'charter-half-day-deep-sea-fishing',
    enabled: true,
    deleted: false,
    slug: 'inshore-reef-light-tackle-catch-release',
    href: '/tours/inshore-reef-light-tackle-catch-release',
    badge: 'Tourists, families, beginners',
    showBadge: true,
    title: 'Half‑Day Deep‑Sea Fishing Charter',
    showTitle: true,
    price: 'Contact for pricing',
    priceLabel: 'Contact for pricing',
    showPrice: true,
    rating: 4.8,
    showRating: true,
    duration: '4h',
    showDuration: true,
    imageUrl:
      'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/tours/1787373076710-26uaezbkmqhj.jpg',
    heroImageUrl: '/images/hero/hero.jpg',
    heroBackgroundColor: '#193da9',
    indicatorColor: '#ffffff',
    location: 'watamu coastal line',
    showLocation: true,
    schedule: 'Any day',
    showSchedule: true,
    groupType: 'Families · Private · Groups',
    showGroupType: true,
    description:
      'Experience the thrill of deep‑sea fishing in Kenya without committing to a full day. Target tuna, dorado, and sailfish while enjoying the ocean views.',
    overview:
      'Enjoy the thrill of offshore fishing in Kenya without committing to a full day. This half‑day adventure is perfect for families, tourists, and beginners who want to experience the excitement of deep‑sea fishing while still having time to relax onshore. Guided by our expert crew, you’ll head into the Indian Ocean to target species such as tuna, dorado, sailfish, and kingfish.\n\nThis shorter trip balances action and comfort, giving you a taste of big‑game fishing while keeping the schedule flexible for sightseeing or beach activities later in the day.',
    included: [
      'Live bait & fishing lures',
      'Light snacks and soft drinks',
      'Fishing equipment provided',
      'Experienced crew & captain guidance',
    ],
    showIncluded: true,
    whyChoose: [],
    showWhyChoose: false,
    knowBeforeYouGo: [
      'Bring sunscreen, hat, sunglasses, and light clothing for sun protection.',
      'Carry seasickness medication if prone to motion sickness.',
      'Keep valuables safe and waterproof (phone, camera).',
      'Catch‑and‑release is encouraged for billfish (sailfish) to support conservation.',
      'Minimum age recommended: 8 years (children must be accompanied by adults).',
      'Trips are weather‑dependent; rescheduling may occur for safety.',
    ],
    showKnowBeforeYouGo: true,
    notIncluded: [
      'Crew gratuities and tips (optional)',
      'Hotel pickup & return transfers',
      'Personal swimwear & towels',
    ],
    showNotIncluded: true,
    gallery: [
      'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/tours/1787373125672-2syo44xjkfk.jpg',
      'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/tours/1787373033806-x1wt9g7q5dr.jpg',
      'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/tours/1787373008978-u6z793wwtkc.jpg',
      'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/tours/1787372967665-nruev4uiv2.jpg',
      '/images/hero/hero.jpg',
      '/images/hero/hero.jpg',
    ],
  },
  {
    id: 'charter-deep-sea-yellowfin-tuna-dorado-trolling',
    enabled: true,
    deleted: false,
    slug: 'deep-sea-yellowfin-tuna-dorado-trolling',
    href: '/tours/deep-sea-yellowfin-tuna-dorado-trolling',
    badge: 'Action Packed',
    showBadge: true,
    title: 'Deep Sea Yellowfin Tuna & Dorado Trolling',
    showTitle: true,
    price: 'Contact for pricing',
    priceLabel: 'Contact for pricing',
    showPrice: true,
    rating: 4.9,
    showRating: true,
    duration: '6h',
    showDuration: true,
    imageUrl: '/images/hero/hero.jpg',
    heroImageUrl: '/images/hero/hero.jpg',
    heroBackgroundColor: '#58595a',
    indicatorColor: '#ffffff',
    location: 'North Kenya Banks & Offshore Drop-Off',
    showLocation: true,
    schedule: 'Morning Slots (August To March)',
    showSchedule: true,
    groupType: 'Sportfishers · Private Charters · Anglers',
    showGroupType: true,
    description:
      'High-speed trolling and live-baiting off the drop-off for acrobatic mahi-mahi (dorado), hard-fighting wahoo, and schooling yellowfin tuna.',
    overview:
      'Experience high-speed trolling and live-baiting off the North Kenya Banks and offshore drop-off for acrobatic mahi-mahi (dorado), hard-fighting wahoo, and schooling yellowfin tuna with our tournament-rigged sportfisher.',
    included: [
      'Live bait & trolling lures',
      'Penn & Shimano trolling rods',
      'Refreshments & iced drinks',
      'Experienced skipper & crew',
    ],
    showIncluded: true,
    whyChoose: ['Decades of local fishing experience', 'Modern rigged tournament boat'],
    showWhyChoose: true,
    knowBeforeYouGo: ['Departure: 6:00 AM', 'What to bring: Sunscreen, hat, sunglasses'],
    showKnowBeforeYouGo: true,
    notIncluded: [
      'Crew gratuities and tips (optional)',
      'Hotel pickup & return transfers',
      'Personal swimwear & towels',
    ],
    showNotIncluded: true,
    gallery: [
      '/images/hero/hero.jpg',
      '/images/hero/hero.jpg',
      '/images/hero/hero.jpg',
    ],
  },
];

/**
 * Default config for this deployment.
 */
export const defaultConfig: AppConfig = {
  branding: {
    font: 'inter',
    appName: 'Sea Smoke kenya',
    logoUrl: 'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/brand/logos/1787336104916-oerjgungn88.png',
    darkMode: false,
    faviconUrl: '/brand/favicons/favicons/1787336104916-oerjgungn88.ico',
    accentColor: '#f6ab03',
    primaryColor: '#193da9',
    metaDescription: 'Premier big-game sportfishing charters, marlin & sailfish safaris, and coastal expeditions on the Kenyan Coast.',
  },

  features: {
    tours: true,
    reports: true,
    bookings: true,
    clientPortal: false,
    notifications: true,
  },

  navigation: [
    {
      key: 'home',
      href: '/',
      icon: 'Home',
      label: 'Home',
      enabled: true,
    },
    {
      key: 'tours',
      href: '/tours',
      icon: 'Ship',
      label: 'Fishing Charters',
      enabled: true,
    },
    {
      key: 'contact',
      href: '/contact',
      icon: 'Mail',
      label: 'Contact',
      enabled: true,
    },
    {
      key: 'about',
      href: '/about',
      icon: 'Info',
      label: 'About',
      enabled: true,
    },
  ],

  homepage: {
    sectionOrder: [
      'stats',
      'tours',
      'whyus',
      'reviews',
      'gallery',
      'cta',
    ],
    hero: {
      size: 'fullscreen',
      enabled: true,
      eyebrow: 'Sea Smoke Kenya – Deep‑Sea Fishing Charters',
      headline: 'Catch Marlin, Sailfish, and Tuna off the Watamu ',
      imageUrl: '/images/hero/hero.jpg',
      subtitle: 'Join Sea Smoke Kenya – Fishing Charters for unforgettable deep‑sea fishing adventures on the Indian Ocean. Our experienced crew will guide you to Kenya’s best fishing grounds, where you can target marlin, sailfish, tuna, and dorado. Whether you’re a beginner or seasoned angler, we provide professional gear, personalized guidance, and a safe, exciting trip that delivers both adventure and memories.',
      italicText: 'Kenya Coast line',
      showEyebrow: true,
      showSubtitle: true,
      primaryCtaHref: '/bookings',
      showPrimaryCta: true,
      primaryCtaLabel: 'Book Your Fishing Trip',
      secondaryCtaHref: '/events',
      showSecondaryCta: true,
      secondaryCtaLabel: 'View Packages & Prices',
    },
    stats: {
      items: [
        {
          label: 'Years of Deep‑Sea Fishing in Kenya',
          value: '7+',
          enabled: true,
        },
        {
          label: 'Happy Anglers Served',
          value: '500+',
          enabled: true,
        },
        {
          label: 'Trophy Fish Landed',
          value: '1500+',
          enabled: true,
        },
        {
          label: 'by Fishing Enthusiasts',
          value: '4.9/5',
          enabled: true,
        },
      ],
      title: '',
      enabled: true,
      eyebrow: '',
      subtitle: '',
      backgroundColor: '#ffffff',
    },
    tours: {
      items: defaultTourItems,
      title: 'Deep Sea Fishing Experiences',
      enabled: true,
      eyebrow: 'Our Fishing Charters',
      subtitle: 'Book unforgettable deep‑sea fishing charters in Kenya with Sea Smoke Kenya. Catch trophy fish like marlin, sailfish, and tuna with expert captains off the Watamu and Mombasa coast.',
      backgroundColor: '#fafafa',
    },
    whyUs: {
      items: [
        {
          body: 'Fish with captains who have decades of experience on the Kenyan coast. Our team knows the best spots for marlin, sailfish, and tuna, ensuring every trip is unforgettable.',
          icon: 'Shield',
          title: 'Expert Crew & Local Knowledge',
          enabled: true,
        },
        {
          body: 'Enjoy members‑only tournaments, private charters, and gear demonstrations. Whether you’re a beginner or seasoned angler, we create tailored experiences for every guest.',
          icon: 'Globe',
          title: 'Exclusive Adventures',
          enabled: true,
        },
        {
          body: 'We practice sustainable catch‑and‑release fishing to protect Kenya’s marine life. Join us in preserving the ocean while enjoying world‑class sport fishing.',
          icon: 'Leaf',
          title: 'Conservation First',
          enabled: true,
        },
        {
          body: '...',
          icon: 'Star',
          title: 'New Feature',
          enabled: false,
        },
      ],
      title: 'Guided by expertise, inspired by the ocean',
      enabled: true,
      eyebrow: 'Why Fish With Us',
      imageUrl: 'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/whyus/1787373732576-brm39503o7p.jpg',
      subtitle: '',
      backgroundColor: '#ffffff',
    },
    gallery: {
      items: [
        {
          caption: 'Giant Marlin Catch',
          enabled: true,
          imageUrl: 'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/gallery/1787251949334-70c5fdfmycp.jpg',
        },
        {
          caption: 'Summer Tournament 2024',
          enabled: true,
          imageUrl: 'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/gallery/1787251823501-26ct9rs424u.jpg',
        },
        {
          caption: 'Sunset Fishing',
          enabled: true,
          imageUrl: 'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/gallery/1787251921286-6q79v31070g.jpg',
        },
        {
          caption: 'Group Trip',
          enabled: true,
          imageUrl: 'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/gallery/1787251933311-lin60r0e4ra.jpg',
        },
        {
          caption: 'New Image',
          enabled: true,
          imageUrl: 'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/tours/1787372983664-kfjlbdy1jc.jpg',
        },
        {
          caption: 'New Image',
          enabled: true,
          imageUrl: 'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/whyus/1787373732576-brm39503o7p.jpg',
        },
        {
          caption: 'New Image',
          enabled: true,
          imageUrl: 'https://zkrrshkjdhdyzfzyjtmt.supabase.co/storage/v1/object/public/media/tours/1787373076710-26uaezbkmqhj.jpg',
        },
      ],
      title: 'Catch Gallery',
      enabled: true,
      eyebrow: '',
      subtitle: '',
      indicatorColor: '#000000',
      backgroundColor: '#ffffff',
    },
    reviews: {
      items: [
        {
          name: 'Michael Thompson',
          quote: '"Joining Sea Smoke Kenya was the best decision I ever made. I’ve learned from veteran anglers and made lifelong friends on the water."',
          enabled: true,
          location: 'Local Member',
        },
        {
          name: 'Sarah Jenkins',
          quote: '"The deep‑sea excursions are incredibly well organized. The captains know exactly where the fish are biting. Highly recommend the summer tournament!"',
          enabled: true,
          location: 'Tournament Winner',
        },
        {
          name: 'David & Lisa',
          quote: '"A fantastic community that truly cares about marine conservation. They teach sustainable fishing practices to all new members."',
          enabled: true,
          location: 'Family Members',
        },
      ],
      title: 'Guest reviews',
      enabled: true,
      eyebrow: 'Excellent on TripAdvisor',
      subtitle: '',
      backgroundColor: '#020617',
    },
    ctaBanner: {
      ctaHref: '/bookings',
      enabled: true,
      ctaLabel: 'Book Your Fishing Charter Now',
      headline: 'Ready to Catch the Big One?',
      subtitle: 'Book your Sea Smoke Kenya Deep‑Sea Fishing Charter today and experience thrilling big-game action on the water.',
      backgroundColor: '#193da9',
    },
    footer: {
      contact: {
        email: 'info@seasmokefishingclub.com',
        phone: '+1 (555) 019-8372',
        location: 'Coastal Harbor Marina, Dock 4',
        workingDays: 'Mon - Sun: 5:00 AM - 8:00 PM',
        workingHours: 'Always ready for you',
      },
      enabled: true,
      socials: {
        items: [
          {
            url: '#',
            icon: 'Facebook',
            enabled: true,
          },
          {
            url: '#',
            icon: 'Instagram',
            enabled: true,
          },
          {
            url: '#',
            icon: 'Whatsapp',
            enabled: true,
          },
          {
            url: '#',
            icon: 'Tiktok',
            enabled: true,
          },
        ],
        enabled: true,
      },
      quickLinks: {
        items: [
          {
            href: '/',
            label: 'Home',
            enabled: true,
          },
          {
            href: '#',
            label: 'Events',
            enabled: true,
          },
          {
            href: '#',
            label: 'Membership',
            enabled: true,
          },
        ],
        enabled: true,
      },
      bottomLinks: {
        items: [
          {
            href: '#',
            label: 'Privacy Policy',
            enabled: true,
          },
          {
            href: '#',
            label: 'Terms & Conditions',
            enabled: true,
          },
        ],
        enabled: true,
      },
      description: 'A passionate community of anglers dedicated to the sport of fishing and marine conservation. Join us on the water.',
      topPackages: {
        items: [
          {
            href: '#',
            label: 'Deep Sea Charter',
            enabled: true,
          },
          {
            href: '#',
            label: 'Inshore Fishing',
            enabled: true,
          },
          {
            href: '#',
            label: 'Tournament Entry',
            enabled: true,
          },
          {
            href: '#',
            label: 'Beginner Classes',
            enabled: true,
          },
          {
            href: '#',
            label: 'Gear Rental',
            enabled: true,
          },
        ],
        enabled: true,
      },
      backgroundColor: '#020617',
    },
  },

  aboutPage: {
    hero: {
      size: 'large',
      enabled: true,
      eyebrow: 'OUR HERITAGE',
      headline: 'Born on the tides,',
      imageUrl: '/images/hero/hero.jpg',
      subtitle: 'Pioneering premier big-game sportfishing and marine conservation along the pristine Kenyan coastline.',
      italicText: 'bound by the deep',
      showEyebrow: true,
      showSubtitle: true,
      primaryCtaHref: '',
      showPrimaryCta: false,
      backgroundColor: '#000000',
      primaryCtaLabel: '',
      secondaryCtaHref: '',
      showSecondaryCta: false,
      secondaryCtaLabel: '',
    },
    story: {
      title: "The heartbeat of Kenya's coastal waters and big-game tradition.",
      enabled: true,
      eyebrow: 'OUR VOYAGE',
      imageAlt: 'Sea Smoke Fishing Club crew on the water',
      imageUrl: '/images/hero/hero.jpg',
      paragraphs: [
        {
          text: 'Founded on the rugged shores of the Kenya Coast, Sea Smoke Fishing Club was born from a singular passion: to deliver world-class sportfishing adventures while championing ocean stewardship. For our anglers, a charter into the deep is more than a sport — it is an intimate encounter with the raw power of the open sea.',
          enabled: true,
        },
        {
          text: 'Over 15 years, we have worked alongside coastal maritime communities and marine biologists to pioneer catch-and-release tagging programs, protect vital billfish breeding grounds, and ensure our blue waters thrive for generations of anglers to come.',
          enabled: true,
        },
      ],
      backgroundColor: '#ffffff',
    },
    team: {
      items: [
        {
          name: 'Captain Peter K.',
          role: 'Head Skipper',
          quote: '"The deep blue speaks to those who respect its currents."',
          enabled: true,
          imageUrl: '/images/hero/hero.jpg',
        },
        {
          name: 'Sarah O.',
          role: 'Marine Biologist & Tagging Specialist',
          quote: '"Every billfish tagged brings us closer to understanding our ocean\'s secrets."',
          enabled: true,
          imageUrl: '/images/hero/hero.jpg',
        },
        {
          name: 'David M.',
          role: 'Master Navigator',
          quote: '"The ocean has a memory; we read every ripple and reef."',
          enabled: true,
          imageUrl: '/images/hero/hero.jpg',
        },
      ],
      title: 'Meet your skippers & naturalists',
      enabled: true,
      eyebrow: 'THE CREW',
      subtitle: "Our crew members aren't just master captains; they are custodians of the Indian Ocean, carrying decades of maritime instincts.",
      backgroundColor: '#ffffff',
    },
    values: {
      items: [
        {
          icon: 'Anchor',
          title: 'Marine Conservation',
          enabled: true,
          description: 'Pioneering strict billfish catch-and-release protocols and active marine habitat preservation.',
        },
        {
          icon: 'Compass',
          title: 'Master Seamanship',
          enabled: true,
          description: 'Seasoned captains with decades of navigational mastery across the East African swell.',
        },
        {
          icon: 'Users',
          title: 'Community & Craft',
          enabled: true,
          description: 'Empowering coastal fishing communities through fair maritime partnerships and training.',
        },
        {
          icon: 'Star',
          title: 'Unmatched Excellence',
          enabled: true,
          description: 'State-of-the-art sportfishing rigs, tournament-grade tackle, and bespoke hospitality at sea.',
        },
      ],
      title: 'Guided by the tides',
      enabled: true,
      eyebrow: 'CORE VALUES',
      subtitle: 'Our core values steer every expedition we launch, every hook we set, and every relationship we nurture on and off the water.',
      backgroundColor: '#fafafa',
    },
    impact: {
      stats: [
        {
          label: 'BILLFISH TAGGED & RELEASED',
          value: '1,200+',
          enabled: true,
        },
        {
          label: 'YEARS OF VOYAGES',
          value: '15+',
          enabled: true,
        },
        {
          label: 'CATCH & RELEASE BILLFISH',
          value: '100%',
          enabled: true,
        },
        {
          label: 'COASTLINE MONITORED',
          value: '350nm',
          enabled: true,
        },
      ],
      title: 'Our impact by the numbers',
      enabled: false,
      subtitle: "Marine conservation isn't an afterthought; it is our compass. Through every charter, we deliver measurable protection for our oceans.",
      partnersCard: {
        icon: 'ShieldCheck',
        title: 'Our Conservation Partners',
        partners: [
          'The Billfish Foundation',
          'Kenya Wildlife Service',
          'Marine Megafauna',
          'East Africa Ocean Trust',
        ],
      },
      backgroundColor: '#0f172a',
    },
    cta: {
      title: 'Answer the call of the deep',
      enabled: true,
      subtitle: 'Whether chasing trophy marlin on the open banks or enjoying an inshore excursion, your next great maritime adventure begins here.',
      primaryCta: {
        href: '/contact',
        label: 'Book Your Charter',
        enabled: true,
      },
      secondaryCta: {
        href: '/contact',
        label: 'Get in Touch',
        enabled: true,
      },
      backgroundColor: '#fafafa',
    },
  },

  toursPage: {
    hero: {
      size: 'medium',
      enabled: true,
      eyebrow: 'SINGLE DAY TRIPS & EXPEDITIONS',
      headline: 'Fishing Charters',
      imageUrl: '/images/hero/hero.jpg',
      subtitle: 'Join Sea Smoke Kenya for unforgettable deep‑sea fishing charters and coastal excursions along Kenya’s premier waters. Our expert captains will take you to the best fishing grounds where you can target trophy marlin, sailfish, tuna, and giant trevally.',
      italicText: '& Excursions',
      showEyebrow: true,
      showSubtitle: true,
      primaryCtaHref: '',
      showPrimaryCta: false,
      backgroundColor: '#193da9',
      primaryCtaLabel: '',
      secondaryCtaHref: '',
      showSecondaryCta: false,
      secondaryCtaLabel: '',
    },
    tours: {
      items: defaultTourItems,
      title: 'Explore Our Fishing Experiences',
      enabled: true,
      eyebrow: 'OUR FISHING CHARTERS',
      subtitle: 'From relaxed inshore family outings to full-day big game billfish safaris, choose your adventure on the Kenya coastal line',
      backgroundColor: '#f5f5f0',
    },
    metaTitle: 'Fishing Charters & Packages',
    metaDescription: 'Explore our fleet of sportfishing charter packages, from inshore light tackle to full-day offshore marlin safaris in Watamu, Kenya.',
    bookingForm: {
      title: 'Book This Charter',
      enabled: true,
      subtitle: 'Reserve your private expedition on the water.',
      accessKey: '',
      buttonText: 'Submit Reservation',
      fields: [
        {
          id: 'fullName',
          type: 'text',
          label: 'Full Name',
          enabled: true,
          required: true,
          halfWidth: true,
          placeholder: 'e.g. John Doe',
        },
        {
          id: 'email',
          type: 'email',
          label: 'Email Address',
          enabled: true,
          required: true,
          halfWidth: true,
          placeholder: 'name@example.com',
        },
        {
          id: 'phone',
          type: 'tel',
          label: 'Phone Number',
          enabled: true,
          required: true,
          halfWidth: true,
          placeholder: '+254 700 000 000',
        },
        {
          id: 'date',
          type: 'date',
          label: 'Preferred Date',
          enabled: true,
          required: false,
          halfWidth: true,
        },
        {
          id: 'guests',
          type: 'select',
          label: 'Number of Guests',
          enabled: true,
          options: [
            '1 Guest',
            '2 Guests',
            '3 Guests',
            '4 Guests',
            '5 Guests',
            '6-8 Guests (Private Boat)',
            '8+ Large Group',
          ],
          required: false,
          halfWidth: false,
        },
        {
          id: 'transfer',
          type: 'checkbox',
          label: 'Include Hotel Pick & Drop Transfer',
          enabled: true,
          required: false,
          halfWidth: false,
        },
        {
          id: 'notes',
          type: 'textarea',
          label: 'Special Requests & Notes',
          enabled: true,
          required: false,
          halfWidth: false,
          placeholder: 'Target species, dietary requirements, experience level...',
        },
        {
          id: 'field_1787345621992',
          type: 'select',
          label: 'New Field',
          enabled: true,
          options: [
            'avb',
            'sds',
          ],
          required: false,
          halfWidth: false,
          placeholder: 'Enter details...',
        },
      ],
    },
  },

  contactPage: {
    hero: {
      size: 'medium',
      enabled: true,
      eyebrow: 'Get in Touch',
      headline: "Let's plan your",
      imageUrl: '/images/hero/hero.jpg',
      subtitle: 'Have a question about our charters or want to book a trip? Our team is ready to help you plan your perfect day on the water.',
      italicText: 'adventure',
      showEyebrow: true,
      showSubtitle: true,
      primaryCtaHref: '',
      showPrimaryCta: false,
      backgroundColor: '#000000',
      primaryCtaLabel: '',
      secondaryCtaHref: '',
      showSecondaryCta: false,
      secondaryCtaLabel: '',
    },
    contact: {
      email: 'info@seasmokekenya.com',
      phone: '+254 123 456 789',
      enabled: true,
      location: 'Mombasa, Kenya',
      whatsapp: '+254 123 456 789',
      locationLink: 'https://maps.google.com/?q=Mombasa',
      backgroundColor: '#f5f5f0',
      tripAdvisorLink: 'https://tripadvisor.com',
    },
    form: {
      title: 'Send a message',
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Full Name',
          enabled: true,
          required: true,
          halfWidth: true,
          placeholder: 'Jane Doe',
        },
        {
          id: 'email',
          type: 'email',
          label: 'Email Address',
          enabled: true,
          required: true,
          halfWidth: true,
          placeholder: 'jane@example.com',
        },
        {
          id: 'phone',
          type: 'tel',
          label: 'Phone Number',
          enabled: true,
          required: false,
          halfWidth: true,
          placeholder: '+254 ...',
        },
        {
          id: 'subject',
          type: 'select',
          label: 'Subject',
          enabled: true,
          options: [
            'General Inquiry',
            'Fishing Charter Booking',
            'Tournaments & Events',
            'Custom Coastal Safari',
            'Feedback & Questions',
          ],
          required: false,
          halfWidth: true,
        },
        {
          id: 'message',
          type: 'textarea',
          label: 'Your Message',
          enabled: true,
          required: true,
          halfWidth: false,
          placeholder: 'Tell us about your next big fishing trip...',
        },
      ],
      enabled: true,
      subtitle: 'We usually respond within 2-4 hours.',
      accessKey: '0d68a0e7-cd00-48c8-86f3-4fab7af13020',
      buttonText: 'Submit request',
      backgroundColor: '#ffffff',
    },
    faq: {
      items: [
        {
          answer: 'The peak season runs from August to March when Marlin and Sailfish are most abundant in Kenyan waters.',
          enabled: true,
          question: 'What is the best time for deep sea fishing?',
        },
        {
          answer: 'No, all premium rods, reels, and tackle are provided on our charters. However, you\'re welcome to bring your favorite gear.',
          enabled: true,
          question: 'Do I need to bring my own fishing gear?',
        },
        {
          answer: 'We strictly enforce a catch-and-release policy for all Billfish (Marlin, Sailfish) to support marine conservation efforts.',
          enabled: true,
          question: 'Is it catch and release?',
        },
      ],
      title: 'Commonly asked questions',
      enabled: true,
      eyebrow: 'QUICK ANSWERS',
      subtitle: '',
      backgroundColor: '#f5f5f0',
    },
    metaTitle: 'Contact & Reservations',
    metaDescription: 'Get in touch with our booking desk to plan your custom fishing trip, big game charter, or private boat excursion.',
  },
};
